version: "3.9"
services:
  mysql:
    image: "mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=employees
      # So you don't have to use root, but you can if you like
      - MYSQL_USER=user
      # You can use whatever password you like
      - MYSQL_PASSWORD=password
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - .db:/var/lib/mysql
# Names our volume
volumes:
  my-db:
